services:
  wdidd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_FASTAPI_URI=${VITE_FASTAPI_URI}
    env_file:
      - .env
    ports:
      - "3000:80"
    restart: always